name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        USERNAME: root
      run: |
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
        ssh $USERNAME@$SERVER_IP 'bash -s' < ./deploy.sh
